/*******************************************************************************
 * lt/system/crashdump/LTSystemCrashdumpPlugin.h
 *
 * This is the Object API implemented by crashdump upload plugins
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, you can obtain one at
 * https://mozilla.org/MPL/2.0/.
 *
 * Copyright 2026, Roku, Inc.  All rights reserved.
 ******************************************************************************/

#ifndef ROKU_LT_INCLUDE_LT_SYSTEM_CRASHDUMP_LTSYSTEMCRASHDUMPPLUGIN_H_
#define ROKU_LT_INCLUDE_LT_SYSTEM_CRASHDUMP_LTSYSTEMCRASHDUMPPLUGIN_H_

#include <lt/LTObject.h>
#include <lt/core/LTThread.h>
#include <lt/system/crashdump/LTSystemCrashdumpAccessWrapper.h>

LT_EXTERN_C_BEGIN

/* Events generated by the specializations of the plugin. All callers should supply a callback
 * of the type LTSystemCrashdump_EventProc that can handle these events. */
typedef enum {
    kLTSystemCrashdump_Event_UploadFailed,
    kLTSystemCrashdump_Event_UploadComplete,
    kLTSystemCrashdump_Event_NoDump,
} LTSystemCrashdump_Event;

typedef void (LTSystemCrashdump_EventProc)(LTSystemCrashdump_Event event, void *pData);
    /**< Callback function type, supplied by the users of an LTSsystemCrashdumpPlugin for
     *   reporting the current state of the crashdump upload.
     *
     *   @param[in] event one of the constants in \a LTSystemCrashdump_Event
     *   @param[in] pData Pointer to data provisioned by the users when registering  */

typedef_LTObject(LTSystemCrashdumpPlugin, 1) {
    void (* OnUploadEvent)(LTSystemCrashdumpPlugin *plugin, LTSystemCrashdump_EventProc *proc, LTThread_ClientDataReleaseProc *releaseProc, void *pData);
    /**< Registers for upload events supplied by \a plugin
     *
     *   @param[in] plugin      upload plugin instance
     *   @param[in] proc        callback to report upload events
     *   @param[in] releaseProc callback for when the user unregisters or when the plugin's internal
     *                          upload event is destroyed while \a proc is still registered for
     *                          upload event notifications
     *   @param[in] pData       data to be passed to the callback \a proc when notified about
     *                          upload events */

    void (* NoUploadEvent)(LTSystemCrashdumpPlugin *plugin, LTSystemCrashdump_EventProc *proc);
    /**< Unregisters for upload events supplied by \a plugin
     *
     *   @param[in] plugin      upload plugin instance
     *   @param[in] proc        callback previously supplied for reporting upload events */

    void (* StartUpload)(LTSystemCrashdumpPlugin *plugin);
    /**< Signals to the plugin to query for a crashdump and upload it if available
     *
     *   @param[in] plugin      upload plugin instance */

    bool (* CrashdumpErase)(LTSystemCrashdumpPlugin *plugin);
    /**< Requests that the plugin asks the underlying crashdump system to delete any existing
     *   crashdumps
     *
     *   @param[in] plugin      upload plugin instance
     *   @returns               true if the crashdump is erased, false otherwise
     *
     *   In most cases, a crashdump will be deleted upon request. Currently, the only reason for
     *   this API to return false is a flash access error. */

    void (* SetCrashdumpAccessWrapper)(LTSystemCrashdumpPlugin *plugin, LTSystemCrashdumpAccessWrapper *wrapper);
    /**< Specifies the use of a custom wrapper to access crashdump data
     *
     *   @param[in] plugin      upload plugin instance
     *   @param[in] wrapper     custom wrapper to access crashdump data
     *
     *   The wrapper is used to access the crashdump data. Calling this API function is optional; if it is not
     *   called, crashdump data is accessed through direct calls to the LTSystemCrashdump API.
     *
     *   @note  If the plugin provides a "standard" wrapper (typically providing crashdump access through direct
     *          calls to LTSystemCrashdump), it will dispose of such a wrapper when that wrapper is replaced via
     *          the first call to this API function.  It is the caller's responsibility to manage the lifetime
     *          of any access wrapper it provides to this function. */
} LTOBJECT_API;

LT_EXTERN_C_END
#endif

/*******************************************************************************
 *  LOG
 *******************************************************************************
 *  04-Jun-24   commodus    created
 */
